lorom
math pri on
arch 65816
check bankcross off

incsrc "functions.asm"
incsrc "registers.asm"
incsrc "registers_spc.asm"

incsrc "bank_00.asm"
incsrc "bank_01.asm"
incsrc "bank_02.asm"
incsrc "bank_03.asm"
incsrc "bank_04.asm"
incsrc "bank_05.asm"
incsrc "bank_06.asm"
incsrc "bank_07.asm"
incsrc "bank_08.asm"
incsrc "bank_09.asm"
incsrc "bank_0A.asm"
incsrc "bank_0B.asm"
incsrc "bank_0C.asm"
incsrc "bank_0D.asm"
incsrc "bank_0E.asm"
incsrc "bank_0F.asm"
incsrc "bank_10.asm"
incsrc "bank_11.asm"
incsrc "bank_12.asm"
incsrc "bank_13.asm"
incsrc "bank_14.asm"
incsrc "bank_15.asm"
incsrc "bank_16.asm"
incsrc "bank_17.asm"
incsrc "bank_18.asm"
incsrc "bank_19.asm"
incsrc "bank_1A.asm"
incsrc "bank_1B.asm"
incsrc "bank_1C.asm"
incsrc "bank_1D.asm"
incsrc "bank_1E.asm"
incsrc "bank_1F.asm"
